name: CI


on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Add and update submodule
        run: |
          git submodule add https://github.com/augustovictor/workflows .github/workflows
          git submodule foreach --recursive git pull

